[package]
name = "carv_learn_to_earn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "carv_learn_to_earn"

[features]
no-entrypoint = []
default = []

[dependencies]
anchor-lang = "0.30.0"
